### ISSUE TITLE
Review pdf titles

### ISSUE THREAD

**Issue by juoceano** [juoceano/geochemistry#1]
@ocefpaf
- [ ] Review bug with pdf titles. 
- [ ] Review latex compilation warning
- [ ] review pdf tex

**Comment by ocefpaf** [comment]
#1 fixes
- [X] Review bug with pdf titles.
- [X] Review latex compilation warning
- [ ] Review pdf tex... In progress.

**Comment by juoceano** [comment]
@ocefpaf 
Ready to be read.
